steps:
  ########
  # SETUP
  ########
- name: 'gcr.io/cloud-builders/docker'
  dir: 'scripts/asm-installer'
  id: 'build-tester-image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'scripts/asm-installer'
  id: 'publish-tester-image'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
  waitFor: ['build-tester-image']

- name: 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
  dir: 'scripts/asm-installer'
  id: 'lint-with-shellcheck'
  entrypoint: 'shellcheck'
  args:
  - '${_SCRIPT_NAME}'
  waitFor:
  - 'publish-tester-image'

    # Disabled for now, see #296. We have more users with LTS Linux releases
    # than non-Bourne shells. Please open an issue if you're affected.
    #- name: 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
    #  dir: 'scripts/asm-installer'
    #  id: 'check-posh-compatibility'
    #  entrypoint: 'posh'
    #  args: ['-n', '${_SCRIPT_NAME}']
    #  waitFor:
    #  - 'publish-tester-image'

- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'scripts/asm-installer'
  id: 'fetch-secrets'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    date
    gcloud secrets versions access latest \
    --secret="${_SECRET_NAME}" \
    --format='get(payload.data)' \
    --project="${PROJECT_ID}" \
    | tr '_-' '/+' \
    | base64 -d > "${_KEY_FILE}"
  waitFor:
  - 'lint-with-shellcheck'

  #############
  # FAST TESTS
  #############
- name: 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
  dir: 'scripts/asm-installer'
  id: 'run-cli-tests'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - >
    ./tests/run_cli_tests
  waitFor:
  - 'fetch-secrets'
  env:
  - '_CI_ASM_IMAGE_LOCATION=${_IMAGE_LOCATION}'
  - '_CI_ASM_PKG_LOCATION=${_PKG_LOCATION}'
  - '_CI_ASM_KPT_BRANCH=${_ASM_PKG_BRANCH}'
  - 'SERVICE_ACCOUNT=${_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com'
  - 'KEY_FILE=${_KEY_FILE}'
  timeout: 120s

- name: 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
  dir: 'scripts/asm-installer'
  id: 'run-print-config-test'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - >
    ./tests/run_print_config_test
  waitFor:
  - 'fetch-secrets'
  env:
  - '_CI_ASM_IMAGE_LOCATION=${_IMAGE_LOCATION}'
  - '_CI_ASM_PKG_LOCATION=${_PKG_LOCATION}'
  - '_CI_ASM_KPT_BRANCH=${_ASM_PKG_BRANCH}'
  - 'SERVICE_ACCOUNT=${_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com'
  - 'KEY_FILE=${_KEY_FILE}'
  - '_CI_ASM_IMAGE_LOCATION=${_IMAGE_LOCATION}'
  - '_CI_ASM_PKG_LOCATION=${_PKG_LOCATION}'
  - '_CI_ASM_KPT_BRANCH=${_ASM_PKG_BRANCH}'
  timeout: 120s

  #############
  # SLOW TESTS
  #############

substitutions:
  _BUCKET_NAME: my-gcs-bucket
  _CLUSTER_LOCATION: us-central1-c
  _IMAGE_NAME: gcloud-with-kpt
  _SCRIPT_NAME: install_asm
  _ASM_PKG_BRANCH: ""
  _SERVICE_ACCOUNT: asm-installer
  _SECRET_NAME: asm-installer-creds
  _KEY_FILE: key.json
timeout: 3600s # 1 hour
