steps:
  ########
  # SETUP
  ########

  #############
  # FAST TESTS
  #############

  #############
  # SLOW TESTS
  #############

substitutions:
  _BUCKET_NAME: my-gcs-bucket
  _CLUSTER_LOCATION: us-central1-c
  _IMAGE_NAME: gcloud-with-kpt
  _SCRIPT_NAME: install_asm
  _ASM_VM_SCRIPT_NAME: asm_vm
  _ASM_PKG_BRANCH: ""
  _SERVICE_ACCOUNT: asm-installer
  _SECRET_NAME: asm-installer-creds
  _KEY_FILE: key.json
timeout: 3600s # 1 hour
