steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'scripts/asm-installer'
    id: 'fetch-secrets'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        date
        gcloud secrets versions access latest \
        --secret="${_SECRET_NAME}" \
        --format='get(payload.data)' \
        --project="${PROJECT_ID}" \
        | tr '_-' '/+' \
        | base64 -d > "${_KEY_FILE}"

  - name: 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
    dir: 'scripts/asm-installer'
    id: 'run-install-custom-cert-suite'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - >
        ./tests/run_install_custom_cert_suite
        --PROJECT_ID "${PROJECT_ID}"
        --BUILD_ID "${BUILD_ID}"
    env:
      - 'SERVICE_ACCOUNT=${_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com'
      - 'KEY_FILE=${_KEY_FILE}'
      - '_CI_ASM_IMAGE_LOCATION=${_IMAGE_LOCATION}'
      - '_CI_ASM_PKG_LOCATION=${_PKG_LOCATION}'
      - '_CI_ASM_KPT_BRANCH=${_ASM_PKG_BRANCH}'
    timeout: 1200s

substitutions:
  _BUCKET_NAME: my-gcs-bucket
  _CLUSTER_LOCATION: us-central1-c
  _IMAGE_NAME: gcloud-with-kpt
  _SCRIPT_NAME: install_asm
  _ASM_VM_SCRIPT_NAME: asm_vm
  _ASM_PKG_BRANCH: $COMMIT_SHA
  _SERVICE_ACCOUNT: asm-installer
  _SECRET_NAME: asm-installer-creds
  _KEY_FILE: key.json
timeout: 3600s # 1 hour
