timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'

# Decrypt the file containing the key
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=cnrm-blueprints-cb-keyring
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Configure the account's default identity
- name: 'gcr.io/cloud-builders/git'
  args:
  - config
  - --global
  - user.email
  - "anthos-blueprints-validation-bot@google.com"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Configure the account's default identity
- name: 'gcr.io/cloud-builders/git'
  args:
  - config
  - --global
  - user.name
  - "anthos-blueprints-validation-bot"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Connect to the blueprints repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - ${_CNRM_BLUEPRINTS_REPO_URL}
  - ${_CNRM_BLUEPRINTS_REPO_NAME}
  - --recursive
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Update the cnrm-blueprints repository if current repo is updated
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sha=$(git submodule status ${_CNRM_BLUEPRINTS_SUBMODULE_PATH} | grep ${COMMIT_SHA})
    if [[ -z $sha ]]; then git submodule update --remote && git add -u && git commit -m "Update the submodule: $REPO_NAME" && git push origin master; fi
  dir: ${_CNRM_BLUEPRINTS_REPO_NAME}
  volumes:
  - name: 'ssh'
    path: /root/.ssh

substitutions:
  _CNRM_BLUEPRINTS_REPO_URL: 'git@github.com:GoogleCloudPlatform/cnrm-blueprints.git'
  _CNRM_BLUEPRINTS_REPO_NAME: 'cnrm-blueprints'
  _CNRM_BLUEPRINTS_SUBMODULE_PATH: 'asm-1.6'
