#!/bin/bash

set -ex
set -o pipefail
set +o noclobber
set +o verbose

main() {
  echo "============================================="
  read_args "${@}"
  write_config_context_vm

  echo "[Step 1] Mount Preparation Artifacts to VM ${VM_APP}@${VM_IP}"
  prepare_vm

  echo "[Step 2] Register VM with WorkloadGroup at namespace: ${VM_NAMESPACE}"
  create_workloadgroup

  echo "[Step 3] istioctl x workload entry and copy to vm ${VM_APP}@${VM_IP}"
  configure_vm_transfer_file

  echo "[Step 4] Install Istio Sidecar and Start Istio on VM"
  runagent
}

prepare_vm() {
  cd ${WORK_DIR}
  if [[ ! -e "runagent.sh" ]]; then
    fatal "file runagent.sh does not exists in working dir ${WORK_DIR}"
  fi

  scp -i "${KEY_FILE}" -o StrictHostKeyChecking=no runagent.sh root@${VM_IP}:"${VM_DIR}"
  scp -i "${KEY_FILE}" -o StrictHostKeyChecking=no istio-sidecar.rpm root@${VM_IP}:"${VM_DIR}"
}

create_workloadgroup() {
  cd ${OUTPUT_DIR}/vm-${VM_APP}

  # Register VM and create a service for the VM
  cat <<EOF >workloadgroup.yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "${VM_APP}"
  namespace: "${VM_NAMESPACE}"
spec:
  metadata:
    labels:
      app: "${VM_APP}"
  template:
    serviceAccount: "${SERVICE_ACCOUNT}"
    network: "${VM_NETWORK}"
EOF

  # add more labels for vm workloadgroup
  if [[ -n "${LABELS}" ]]; then
    tmpLabels=(${LABELS//;/ })
    echo ${tmpLabels[@]}
    for tmplabel in "${tmpLabels[@]}"; do
      curLabels=(${tmplabel//:/ })

      tmplabel0=${curLabels[0]}
      tmplabel0+=":\ \""
      tmplabel0+=${curLabels[1]}
      tmplabel0+="\""

      sed -i -e "10 i \ \ \ \ \ \ $tmplabel0" workloadgroup.yaml
    done
  fi

  kubectl --namespace "${VM_NAMESPACE}" apply -f workloadgroup.yaml
}

configure_vm_transfer_file() {
  # Create files to transfer to VM
  cd ${WORK_DIR}
  ./istioctl x workload entry configure -f ${OUTPUT_DIR}/vm-${VM_APP}/workloadgroup.yaml -o ${OUTPUT_DIR}/vm-${VM_APP} --clusterID ${CLUSTER} --autoregister

  cd ${OUTPUT_DIR}/vm-${VM_APP}
  ssh -i "${KEY_FILE}" -o StrictHostKeyChecking=no root@${VM_IP} mkdir "${VM_DIR}" || true
  scp -i "${KEY_FILE}" -o StrictHostKeyChecking=no cluster.env hosts istio-token mesh.yaml root-cert.pem root@${VM_IP}:"${VM_DIR}"
}

runagent() {
  # SSH to VM and execute runagent.sh on VM
  runagentcmd="chmod +x ${VM_DIR}/runagent.sh; ${VM_DIR}/runagent.sh ${VM_DIR}"
  until ssh -i "${KEY_FILE}" -o StrictHostKeyChecking=no root@${VM_IP} ${runagentcmd}; do
    sleep 1
  done

  echo "============================================="
  echo -e "\xE2\x9C\x94 Under the context of cluster:${CLUSTER} clusterNetwork:${CLUSTER_NETWORK} vmNetwork:${VM_NETWORK}"
  echo -e "\xE2\x9C\x94 successfully add vm:${VM_APP} addr:${VM_IP} sa:${SERVICE_ACCOUNT}" ns:${VM_NAMESPACE}
}

write_config_context_vm() {
  # select different context from current context
  if [[ -n "${SELECT_CONTEXT}" ]]; then
    export CONTEXT="${SELECT_CONTEXT}"
  else
    currContext=$(cat "./.currContext")
    CONTEXT=${currContext:10}
  fi

  if [[ ! -s "./.attachConfig" ]]; then
    # attach vm with no modification of configuration (command only specified app and addr)
    echo "Attach VM with Context: ${CONTEXT}"
    source "./.${CONTEXT}"
  elif [[ $(wc -l "./.attachConfig") == 1 && $(grep -q "export SELECT_CONTEXT=" "./.attachConfig") ]]; then
    # attach vm with only app, addr and context
    echo "Attach VM with Context: ${CONTEXT}"
    source "./.${CONTEXT}"
  else
    # attach vm with some modification on key, or sa, or ns, or labels
    source "./.${CONTEXT}"
    source "./.attachConfig"
  fi

  alias kubectl="kubectl --kubeconfig ${KUBECONFIG}"
  alias istioctl="istioctl --kubeconfig ${KUBECONFIG}"

  if [[ -e ${OUTPUT_DIR}/vm-${VM_APP} ]]; then
    rm -rf ${OUTPUT_DIR}/vm-${VM_APP}
  fi

  if [[ ! -e ${OUTPUT_DIR} ]]; then
    mkdir ${OUTPUT_DIR}
  fi

  NS=$(kubectl get namespace ${VM_NAMESPACE} -o name --ignore-not-found)
  if [[ -z "${NS}" ]]; then
    kubectl create namespace ${VM_NAMESPACE}
  fi

  SA=$(kubectl get serviceaccount "${SERVICE_ACCOUNT}" -n "${VM_NAMESPACE}" -o name --ignore-not-found)
  if [[ -z "${SA}" ]]; then
    kubectl create serviceaccount "${SERVICE_ACCOUNT}" -n "${VM_NAMESPACE}"
  fi

  mkdir -p ${OUTPUT_DIR}/vm-${VM_APP}
  cp ./.${CONTEXT} ${OUTPUT_DIR}/vm-${VM_APP}/".context"

  CONTEXT_FILE=${OUTPUT_DIR}/vm-${VM_APP}/".context"
  chmod 777 ${OUTPUT_DIR}/vm-${VM_APP}/".context"

  echo "export VM_APP=${VM_APP}" >>${CONTEXT_FILE}
  echo "export VM_IP=${VM_IP}" >>${CONTEXT_FILE}
  cat "./.attachConfig" >>${CONTEXT_FILE}
  rm -f ".attachConfig"
  cat ${OUTPUT_DIR}/vm-${VM_APP}/".context"
}

read_args() {
  # shellcheck disable=SC2064
  trap "$(shopt -p nocasematch)" RETURN
  shopt -s nocasematch

  >".attachConfig"
  chmod 777 ".attachConfig"
  while [[ ${#} != 0 ]]; do
    case "${1}" in
    -addr | --address | --vm_ip | --vm-ip)
      export VM_IP="${2}"
      shift 2
      ;;
    -app | --app | --vm_app | --vm-app)
      export VM_APP="${2}"
      shift 2
      ;;
    -context | --context)
      export SELECT_CONTEXT="${2}"
      echo "export SELECT_CONTEXT=${SELECT_CONTEXT}" >>".attachConfig"
      shift 2
      ;;
    -key | --key_file | --ssh-key-file)
      export KEY_FILE="${2}"
      echo "export KEY_FILE=${KEY_FILE}" >>".attachConfig"
      shift 2
      ;;
    -sa | --service_account | --service-account)
      export SERVICE_ACCOUNT="${2}"
      echo "export SERVICE_ACCOUNT=${SERVICE_ACCOUNT}" >>".attachConfig"
      shift 2
      ;;
    -ns | --namespace)
      export VM_NAMESPACE="${2}"
      echo "export VM_NAMESPACE=${VM_NAMESPACE}" >>".attachConfig"
      shift 2
      ;;
    -labels | --labels)
      LABELS="${2}"
      printf -v LABELS '%s' ${LABELS}
      export LABELS="\"${LABELS}\""
      echo "export LABELS=${LABELS}" >>".attachConfig"
      shift 2
      ;;
    *)
      warn "Unknown option ${1}"
      exit 2
      ;;
    esac
  done
}

function warn() {
  info "[WARNING]: ${1}" >&2
}

function apath() {
  "${APATH}" "${@}"
}

function fatal() {
  error "${1}"
  exit 2
}

function info() {
  echo "${SCRIPT_NAME}: ${1}" >&2
}

function error() {
  info "[ERROR]: ${1}" >&2
}

main "${@}"
