#!/bin/bash

#set -ex
set -CeE
set -o pipefail
set +o noclobber

main() {
  echo "============================================= create attach context"
  init
  parse_validate_args "${@}"
}

init() {
  # BSD-style readlink apparently doesn't have the same -f toggle on readlink
  case "$(uname)" in
  Linux) APATH="readlink" ;;
  Darwin) APATH="stat" ;;
  *) ;;
  esac
}

function parse_validate_args() {
  # shellcheck disable=SC2064
  trap "$(shopt -p nocasematch)" RETURN
  shopt -s nocasematch

  CONTEXT_FILE=".${1}"
  read_args "${@}"
  fill_unspecified_context
  write_config_context

}

function fill_unspecified_context() {

  if [[ -z "${KUBECONFIG}" ]]; then
    KUBECONFIG="$HOME/.kube/config"
  fi
  alias kubectl="kubectl --kubeconfig ${KUBECONFIG}"

  echo "Using KUBECONFIG ${KUBECONFIG}"
  PROJECT_ID=$(gcloud config get-value project)
  echo "Using PROJECT_ID ${PROJECT_ID}"
  PROJECT_NUMBER=$(gcloud projects describe ${PROJECT_ID} --format="value(projectNumber)")
  echo "Using PROJECT_NUMBER ${PROJECT_NUMBER}"

  # use the absolute path for the key file
  if [[ -f "${KEY_FILE}" ]]; then
    KEY_FILE="$(apath -f "${KEY_FILE}")"
    #    readonly KEY_FILE
  elif [[ -n "${KEY_FILE}" ]]; then
    fatal "Couldn't find key file ${KEY_FILE}. "
  fi

  CLUSTER_NAME=$(kubectl -n istio-system get IstioOperator installed-state --output=json | jq -r '.spec.values.global.multiCluster.clusterName')
  if [[ -z "${CLUSTER}" ]]; then
    CLUSTER=${CLUSTER_NAME}
    echo "Using CLUSTER ${CLUSTER}"
  elif [[ ${CLUSTER_NAME} != ${CLUSTER} ]]; then
    fatal "Current kubeconfig points to cluster: ${CLUSTER_NAME}, cannot connect to input cluster ${CLUSTER}"
  fi

  CLUSTER_NETWORK=$(kubectl -n istio-system get IstioOperator installed-state --output=json | jq -r '.spec.values.global.network')
  if [[ ${CLUSTER_NETWORK} == ${VM_NETWORK} ]]; then
    echo "Using Single-Network Scenario. Cluster and VM are Running in Network: ${VM_NETWORK}"
  elif [[ -z ${VM_NETWORK} ]]; then
    echo "VM Network      is not specified. Set VM Network same as Cluster Network ${CLUSTER_NETWORK}. Single-Network Scenario"
    VM_NETWORK=${CLUSTER_NETWORK}
  else
    echo "Using Multi-Network Scenario. Cluster Network: ${CLUSTER_NETWORK}, VM Network: ${VM_NETWORK}"
  fi

  if [[ -z "${MESH_ID}" ]]; then
    MESH_ID="proj-${PROJECT_NUMBER}"
    echo "Mesh ID         is not specified. Set Mesh ID as proj-PROJECT_NUMBER: ${MESH_ID}."
  fi

  # name of the Kubernetes service account you want to use for your VM. Set as "default" by default
  if [[ -z "${SERVICE_ACCOUNT}" ]]; then
    echo "Service Account is not specified. Set Service Account as default"
    SERVICE_ACCOUNT="default"
  fi

  if [[ -z "${WORK_DIR}" ]]; then
    WORK_DIR="$(pwd)"
    echo "Working Dir     is not specified. Set Working Dir as ${WORK_DIR}"
    echo "WORK_DIR=${WORK_DIR}" >>${CONTEXT_FILE}
  fi

  if [[ -z "${OUTPUT_DIR}" ]]; then
    OUTPUT_DIR="${WORK_DIR}"
    echo "Output  Dir     is not specified. Set Output Directory for each VM as ${OUTPUT_DIR}/vm-vm_name"
  else
    echo "Set Output Directory for each VM as ${OUTPUT_DIR}/vm-vm_name"
  fi
  echo "OUTPUT_DIR=${OUTPUT_DIR}" >>${CONTEXT_FILE}

  if [[ -z "${VM_NAMESPACE}" ]]; then
    VM_NAMESPACE="default"
    echo "VM NAMESPACE    is not specified. Set VM NAMESPACE as default"
  fi
  NS=$(kubectl get namespace ${VM_NAMESPACE} --ignore-not-found)
  if [[ "${NS}" ]]; then
    echo "Skipping creation of namespace       ${VM_NAMESPACE} - already exists"
  else
    kubectl create namespace ${VM_NAMESPACE}
  fi

  SA=$(kubectl get serviceaccount "${SERVICE_ACCOUNT}" -n "${VM_NAMESPACE}" -o name --ignore-not-found)
  if [[ "${SA}" ]]; then
    echo "Skipping creation of service-account ${SERVICE_ACCOUNT} - already exists"
  else
    kubectl create serviceaccount "${SERVICE_ACCOUNT}" -n "${VM_NAMESPACE}"
  fi

}

function  write_config_context() {
  >${CONTEXT_FILE}
  chmod 777 ${CONTEXT_FILE}

  echo "export WORK_DIR=${WORK_DIR}" >>${CONTEXT_FILE}
  echo "export OUTPUT_DIR=${OUTPUT_DIR}" >>${CONTEXT_FILE}
  echo "export KEY_FILE=${KEY_FILE}" >>${CONTEXT_FILE}
  echo "export KUBECONFIG=${KUBECONFIG}" >>${CONTEXT_FILE}
  echo "export PROJECT_ID=${PROJECT_ID}" >>${CONTEXT_FILE}
  echo "export MESH_ID=${MESH_ID}" >>${CONTEXT_FILE}
  echo "export CLUSTER=${CLUSTER}" >>${CONTEXT_FILE}
  echo "export CLUSTER_NETWORK=${CLUSTER_NETWORK}" >>${CONTEXT_FILE}
  echo "export VM_NETWORK=${VM_NETWORK}" >>${CONTEXT_FILE}
  echo "export VM_NAMESPACE=${VM_NAMESPACE}" >>${CONTEXT_FILE}
  echo "export SERVICE_ACCOUNT=${SERVICE_ACCOUNT}" >>${CONTEXT_FILE}

}

function read_args() {
  shift 1
  while [[ ${#} != 0 ]]; do
    case "${1}" in
    -addr | --address | --vm_ip | --vm-ip)
      export VM_IP="${2}"
      shift 2
      ;;
    -app | --app | --vm_app | --vm-app)
      export VM_APP="${2}"
      shift 2
      ;;
    -mesh | --mesh_id | --mesh-id)
      export MESH_ID="${2}"
      shift 2
      ;;
    -network | --network | --vm_network | --vm-network)
      export VM_NETWORK="${2}"
      shift 2
      ;;
    -k | --key_file | --ssh-key-file)
      export KEY_FILE="${2}"
      shift 2
      ;;
    -s | --service_account | --service-account)
      export SERVICE_ACCOUNT="${2}"
      shift 2
      ;;
    --cluster | --vm-cluster | --cluster_name | --cluster-name)
      export CLUSTER="${2}"
      shift 2
      ;;
    -p | --project_id | --project-id)
      export PROJECT_ID="${2}"
      shift 2
      ;;
    -ns | --namespace)
      export VM_NAMESPACE="${2}"
      shift 2
      ;;
    --kubeconfig)
      export KUBECONFIG="${2}"
      shift 2
      ;;
    --context)
      export SELECT_CONTEXT="${2}"
      shift 2
      ;;
    *)
      warn "Unknown option ${1}"
      exit 2
      ;;
    esac
  done
}

function warn() {
  info "[WARNING]: ${1}" >&2
}

function apath() {
  "${APATH}" "${@}"
}

function fatal() {
  error "${1}"
  exit 2
}

function info() {
  echo "${SCRIPT_NAME}: ${1}" >&2
}

function error() {
  info "[ERROR]: ${1}" >&2
}

main "${@}"