# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout
  namespace: checkout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: checkout
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: checkout
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.9.0
          ports:
          - containerPort: 5050
          readinessProbe:
            grpc:
              port: 5050
          livenessProbe:
            grpc:
              port: 5050
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.product-catalog.svc.cluster.local:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.shipping.svc.cluster.local:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.payment.svc.cluster.local:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.email.svc.cluster.local:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.currency.svc.cluster.local:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.cart.svc.cluster.local:7070"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
