# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  revision: "asm-managed"
  profile: asm-gcp
  hub: gcr.io/gke-release/asm # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.hub"}
  tag: 1.10.2-asm.1 # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.tag"}
  components:
    base:
      enabled: false
    pilot:
      enabled: false
    cni:
      enabled: false
    istiodRemote:
      enabled: false
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        label:
          app: istio-ingressgateway
          istio: ingressgateway
  meshConfig:
    trustDomain: "PROJECT_ID.svc.id.goog" # {"$ref":"#/definitions/io.k8s.cli.substitutions.trust-domain"}
    defaultConfig:
      proxyMetadata:
        CA_ROOT_CA: "/etc/ssl/certs/ca-certificates.crt"
        XDS_ROOT_CA: "/etc/ssl/certs/ca-certificates.crt"
        OUTPUT_CERTS: "/etc/istio/proxy"
        XDS_AUTH_PROVIDER: "gcp"
        XDS_HEADER_Cloud-Run-Enable-H2: "y"
        ISTIO_META_CLOUDRUN_ADDR: "ISTIO_CLOUDRUN_ADDR" # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.managed-controlplane.cloudrun-addr"}
  values:
    gateways:
      istio-ingressgateway:
        runAsRoot: true
    global:
      sds:
        token:
          aud: "PROJECT_ID.svc.id.goog" # {"$ref":"#/definitions/io.k8s.cli.substitutions.trust-domain"}
      meshID: "proj-PROJECT_NUMBER" # {"$ref":"#/definitions/io.k8s.cli.substitutions.mesh-id"}
      multiCluster:
        clusterName: "cn-PROJECT_ID-CLUSTER_LOCATION-CLUSTER_NAME" # {"$ref":"#/definitions/io.k8s.cli.substitutions.cluster-name"}
