apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base # {"$ref":"#/definitions/io.k8s.cli.setters.base-dir"}
- resources
patches:
- path: patches/cluster-patch.yaml
  target:
    kind: ContainerCluster
- path: patches/nodepool-patch.yaml
  target:
    kind: ContainerNodePool
