#!/usr/bin/env bash
main() {
  local FILE; FILE="${1}"
  local FAILED; FAILED=0

  if [[ ! -f "${FILE}" ]]; then
    echo "FAILED: ${FILE}: No such file or directory"
    exit 1
  fi

  while read -r VARIABLE; do
    VARIABLE=${VARIABLE%=}
    if ! grep -Eq "local([[:space:]A-Za-z0-9_\-]+)?${VARIABLE}(;|$|=|[[:space:]])" "${FILE}" \
    && ! grep -Eq "readonly ${VARIABLE}(;|$)" "${FILE}" && ! should_skip "${VARIABLE}"; then
      echo "FAILED: ${VARIABLE} is not marked as local or readonly!"
      FAILED=1
    fi
  done <<EOF
$(get_all_variables "${FILE}")
EOF

  if [[ "${FAILED}" -eq 1 ]]; then
    false
  fi
}

get_all_variables() {
  local FILE; FILE="${1}"
  local VARIABLE_PATTERN; VARIABLE_PATTERN="[[:space:]][A-Z0-9_\-]\+="
  cat "${FILE}" | grep -o "${VARIABLE_PATTERN}" | uniq
}

should_skip() {
  local VARIABLE; VARIABLE="$1"
  if [[ "${VARIABLE}" = "IFS" ]]; then
    true
    return
  fi
  false
}

main "$@"
