#!/bin/bash
set -CeEu
set -o pipefail

SPATH="$(readlink -f "$0")"
SDIR="$(dirname "${SPATH}")"; export SDIR;
SCRIPT_NAME="${0##*/}"

# shellcheck source=common.sh
. "${SDIR}/common.sh"

cd "${SDIR}"

export _CI_ASM_IMAGE_LOCATION="gcr.io/gke-release-staging/asm"

main() {
  # CLI setup
  parse_args "$@"
  local REVISION_LABEL; REVISION_LABEL="$(uniq_name "${SCRIPT_NAME}" "${BUILD_ID}")"

  export OUTPUT_DIR="$(mktemp -d)"
  run_build_offline_package "${OUTPUT_DIR}"

  run_basic_test "install" "mesh_ca" "--revision_name ${REVISION_LABEL} --offline"; RETVAL=$?;

  echo "Verifying service mesh feature is enabled..."
    if ! is_service_mesh_feature_enabled; then
      fatal "Service mesh feature is not enabled."
    fi

  cleanup_lt_cluster "${LT_NAMESPACE}" "${OUTPUT_DIR}" "${REV}"
  delete_service_mesh_feature
  exit "${RETVAL}"
}

main "$@"
