#!/bin/bash
set -CeEu
set -o pipefail

SPATH="$(readlink -f "$0")"
SDIR="$(dirname "${SPATH}")"; export SDIR;
SCRIPT_NAME="${0##*/}"

# shellcheck source=common.sh
. "${SDIR}/common.sh"

cd "${SDIR}"

main() {
  # CLI setup
  parse_args "$@"

  run_basic_test "install" "mesh_ca" "--managed --enable-registration"; RETVAL=$?;

  echo "Verifying service mesh feature is enabled..."
  if ! is_service_mesh_feature_enabled; then
    fatal "Service mesh feature is not enabled."
  fi

  cleanup_lt_cluster "${LT_NAMESPACE}" "${OUTPUT_DIR}" "${REV}"
  delete_service_mesh_feature
  exit "${RETVAL}"
}

main "$@"
