#!/bin/bash

set -ex
set -o pipefail
set +o noclobber
set +o verbose

source util.sh

main() {
  echo "============================================="
  init
  read_args "${@}"
  write_config_context_vm

  echo "[Step 1] Register VM at namespace: ${VM_NAMESPACE}"
  create_workloadgroup

  echo "[Step 2] Copy configuration files to VM: ${VM_APP}@${VM_IP}"
  configure_vm_transfer_file

  echo "[Step 3] Install ASM agent on VM"
  runagent
}

create_workloadgroup() {
  cd ${OUTPUT_DIR}/vm-${VM_APP}

  # Register VM and create a service for the VM
  cat <<EOF >workloadgroup.yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "${VM_APP}"
  namespace: "${VM_NAMESPACE}"
spec:
  metadata:
    labels:
      app: "${VM_APP}"
  template:
    serviceAccount: "${SERVICE_ACCOUNT}"
    network: "${VM_NETWORK}"
EOF

  # add more labels for vm workloadgroup
  if [[ -n "${LABELS}" ]]; then
    tmpLabels=(${LABELS//;/ })
    echo ${tmpLabels[@]}
    for tmplabel in "${tmpLabels[@]}"; do
      curLabels=(${tmplabel//:/ })

      tmplabel0=${curLabels[0]}
      tmplabel0+=":\ \""
      tmplabel0+=${curLabels[1]}
      tmplabel0+="\""

      sed -i -e "10 i \ \ \ \ \ \ $tmplabel0" workloadgroup.yaml
    done
  fi

  kubectl --namespace "${VM_NAMESPACE}" apply -f workloadgroup.yaml
}

configure_vm_transfer_file() {
  # Create files to transfer to VM
  cd ${WORK_DIR}
  ./istioctl x workload entry configure -f ${OUTPUT_DIR}/vm-${VM_APP}/workloadgroup.yaml -o ${OUTPUT_DIR}/vm-${VM_APP} --clusterID ${CLUSTER} --autoregister

  cd ${OUTPUT_DIR}/vm-${VM_APP}
  ssh -i "${KEY_FILE}" -o StrictHostKeyChecking=no root@${VM_IP} mkdir "${VM_DIR}" || true
  scp -i "${KEY_FILE}" -o StrictHostKeyChecking=no cluster.env hosts istio-token mesh.yaml root-cert.pem root@${VM_IP}:"${VM_DIR}"

  cd ${WORK_DIR}
  if [[ ! -e "runagent.sh" ]]; then
    fatal "file runagent.sh does not exists in working dir ${WORK_DIR}"
  fi

  scp -i "${KEY_FILE}" -o StrictHostKeyChecking=no runagent.sh root@${VM_IP}:"${VM_DIR}"

  if [[ ! -e "istio-sidecar.rpm" ]]; then
    fatal "file istio-sidecar.rpm does not exists in working dir ${WORK_DIR}"
  fi
  scp -i "${KEY_FILE}" -o StrictHostKeyChecking=no istio-sidecar.rpm root@${VM_IP}:"${VM_DIR}"
}

runagent() {
  # SSH to VM and execute runagent.sh on VM
  runagentcmd="chmod +x ${VM_DIR}/runagent.sh; ${VM_DIR}/runagent.sh ${VM_DIR}"
  until ssh -i "${KEY_FILE}" -o StrictHostKeyChecking=no root@${VM_IP} ${runagentcmd}; do
    sleep 1
  done

  echo "============================================="
  echo -e "\xE2\x9C\x94 Under the context of cluster:${CLUSTER} clusterNetwork:${CLUSTER_NETWORK} vmNetwork:${VM_NETWORK}"
  echo -e "\xE2\x9C\x94 successfully add vm:${VM_APP} addr:${VM_IP} sa:${SERVICE_ACCOUNT}" ns:${VM_NAMESPACE}
}

write_config_context_vm() {
  # select different context from current context
  if [[ -n "${SELECT_CONTEXT}" ]]; then
    export CONTEXT="${SELECT_CONTEXT}"
  elif [[ ! -e "./.currContext" || ! -s "./.currContext" ]]; then
    # attach vm directly without set context
    export CONTEXT="attachConfig"
  else
    currContext=$(cat "./.currContext")
    export CONTEXT=${currContext:10}
  fi

  source "./.${CONTEXT}"
  source "./.attachConfig"
  fill_unspecified_context

  alias istioctl="istioctl --kubeconfig ${KUBECONFIG}"

  if [[ -e ${OUTPUT_DIR}/vm-${VM_APP} ]]; then
    rm -rf ${OUTPUT_DIR}/vm-${VM_APP}
  fi

  if [[ ! -e ${OUTPUT_DIR} ]]; then
    mkdir ${OUTPUT_DIR}
  fi

  mkdir -p ${OUTPUT_DIR}/vm-${VM_APP}
  CONTEXT_FILE=${OUTPUT_DIR}/vm-${VM_APP}/".context"
  write_config_context

  echo "export VM_APP=${VM_APP}" >>${CONTEXT_FILE}
  echo "export VM_IP=${VM_IP}" >>${CONTEXT_FILE}

  rm -f ".attachConfig"
  cat ${OUTPUT_DIR}/vm-${VM_APP}/".context"
}

read_args_vm() {
  # shellcheck disable=SC2064
  trap "$(shopt -p nocasematch)" RETURN
  shopt -s nocasematch

  >".attachConfig"
  chmod +x ".attachConfig"
  while [[ ${#} != 0 ]]; do
    case "${1}" in
    -addr | --address | --vm_ip | --vm-ip)
      export VM_IP="${2}"
      shift 2
      ;;
    -app | --app | --vm_app | --vm-app)
      export VM_APP="${2}"
      shift 2
      ;;
    -context | --context)
      export SELECT_CONTEXT="${2}"
      echo "export SELECT_CONTEXT=${SELECT_CONTEXT}" >>".attachConfig"
      shift 2
      ;;
    -key | --key_file | --ssh-key-file)
      export KEY_FILE="${2}"
      echo "export KEY_FILE=${KEY_FILE}" >>".attachConfig"
      shift 2
      ;;
    -sa | --service_account | --service-account)
      export SERVICE_ACCOUNT="${2}"
      echo "export SERVICE_ACCOUNT=${SERVICE_ACCOUNT}" >>".attachConfig"
      shift 2
      ;;
    -ns | --namespace)
      export VM_NAMESPACE="${2}"
      echo "export VM_NAMESPACE=${VM_NAMESPACE}" >>".attachConfig"
      shift 2
      ;;
    -labels | --labels)
      LABELS="${2}"
      printf -v LABELS '%s' ${LABELS}
      export LABELS="\"${LABELS}\""
      echo "export LABELS=${LABELS}" >>".attachConfig"
      shift 2
      ;;
    -mesh | --mesh_id | --mesh-id)
      export MESH_ID="${2}"
      shift 2
      ;;
    -net | --network | --vm_network | --vm-network)
      export VM_NETWORK="${2}"
      shift 2
      ;;
    -cluster | --cluster | --cluster_name | --cluster-name)
      export CLUSTER="${2}"
      shift 2
      ;;
    -project | --project | --project_id | --project-id)
      export PROJECT_ID="${2}"
      shift 2
      ;;
    -kubeconfig | --kubeconfig)
      export KUBECONFIG="${2}"
      shift 2
      ;;
    *)
      warn "Unknown option ${1}"
      exit 2
      ;;
    esac
  done
}

main "${@}"
