#!/bin/bash
set -eEuC
set -o pipefail

SPATH="$(readlink -f "$0")"
SDIR="$(dirname "${SPATH}")"; export SDIR;

# shellcheck source=common.sh
. "${SDIR}/common.sh"

main() {
  setup

  get_version_file_and_lock

  # read from a different FD other than stdin
  # during publish we will read from stdin for user confirmation
  while read -r branch version <&3; do
    publish_script "${branch}" "${version}" asmcli
  done 3<<EOF
$(all_releases)
EOF

  upload_version_file_and_unlock
}

main
