---
apiVersion: mesh.cloud.google.com/v1alpha1
kind: ControlPlaneRevision
metadata:
  name: asm-managed-rapid
  namespace: istio-system
  annotations:
    mesh.cloud.google.com/image: "" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gke-mcp-image"}
spec:
  type: managed_service
  channel: rapid
status:
  conditions:
    - message: The provisioning process has completed successfully
      reason: Provisioned
      status: true
      type: Reconciled
    - message: Provisioning has finished
      reason: ProvisioningFinished
      status: true
      type: ProvisioningFinished
    - message: Provisioning has not stalled
      reason: NotStalled
      status: false
      type: Stalled
