#!/bin/bash
set -CeEu
set -o pipefail

SPATH="$(readlink -f "$0")"
SDIR="$(dirname "${SPATH}")"; export SDIR;
SCRIPT_NAME="${0##*/}"

# shellcheck source=common.sh
. "${SDIR}/common.sh"

cd "${SDIR}"

main() {
  # CLI setup
  parse_args "$@"

  sed -i 's/meshconfig\.googleapis\.com/staging-meshconfig.sandbox.googleapis.com/g' ../install_asm
  run_basic_test "install" "mesh_ca" "--managed"; RETVAL=$?;
  sed -i 's/staging-meshconfig.sandbox.googleapis.com/meshconfig\.googleapis\.com/g' ../install_asm
  cleanup_lt_cluster "${LT_NAMESPACE}" "${OUTPUT_DIR}" "${REV}"

  exit "${RETVAL}"
}

main "$@"
