#!/bin/bash
set -CeEu
set -o pipefail

SPATH="$(readlink -f "$0")"
SDIR="$(dirname "${SPATH}")"; export SDIR;

# shellcheck source=common.sh
. "${SDIR}/common.sh"

cd "${SDIR}"
pwd

# We want to not need to create clusters, which means no calling then with
# gcloud and kubectl. So we remove the call to "main" in install_asm, remove the
# "readonly" keywords, and then source the file so all of the functions are
# available. We can then overwrite kubectl and gcloud with functions that point
# to the fake scripts in this directory, and voila! We can mock binaries in the
# script.

head ../install_asm -n -1 | sed -e 's/readonly.*$//g' >| ./fake_install_asm
trap 'rm ./fake_install_asm' EXIT

. ./fake_install_asm

KUBE="$(readlink -f ./fake_kubectl)"
GCL="$(readlink -f ./fake_gcloud)"

clear_variables() {
  PROJECT_ID=""; export PROJECT_ID;
  CLUSTER_NAME=""; export CLUSTER_NAME;
  CLUSTER_LOCATION=""; export CLUSTER_LOCATION;
  MODE=""; export MODE;
  CA=""; export CA;

  OPERATOR_OVERLAY=""; export OPERATOR_OVERLAY;
  ENABLE_ALL=0; export ENABLE_ALL;
  ENABLE_GCP_APIS=0; export ENABLE_GCP_APIS;
  ENABLE_GCP_IAM_ROLES=0; export ENABLE_GCP_IAM_ROLES;
  ENABLE_GCP_COMPONENTS=0; export ENABLE_GCP_COMPONENTS;
  ENABLE_CLUSTER_LABELS=0; export ENABLE_CLUSTER_LABELS;
  ENABLE_CLUSTER_ROLES=0; export ENABLE_CLUSTER_ROLES;
  PRINT_CONFIG=0; export PRINT_CONFIG;
  SERVICE_ACCOUNT=""; export SERVICE_ACCOUNT;
  KEY_FILE=""; export KEY_FILE;

  DRY_RUN=0; export DRY_RUN;
  ONLY_VALIDATE=0; export ONLY_VALIDATE;
  VERBOSE=0; export VERBOSE;
}

kubectl() {
  local RETVAL; RETVAL=0;
  "${KUBE}" ${@} || RETVAL="${?}"
  return "${RETVAL}"
}

gcloud() {
  local RETVAL; RETVAL=0;
  "${GCL}" ${@} || RETVAL="${?}"
  return "${RETVAL}"
}

curl() {
  return 0
}

tar() {
  return 0
}

kpt() {
  return 0
}

test_main() {
  local FAILURES; FAILURES=0;

  #################
  # This should pass
  #################

  local CMD
  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m install"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -eq 0 ]]; then
    echo "Passes on good case: PASS"
  else
    echo "Passes on good case: FAIL"
    ((++FAILURES))
  fi

  #################
  # Should fail on non-existing project
  #################

  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_fail"
  CMD="${CMD} -m install"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} --only-validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on nonexisting projects: PASS"
  else
    echo "Fails on nonexisting projects: FAIL"
    ((++FAILURES))
  fi


  #################
  # Should fail on non-existing cluster
  #################

  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_fail"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m install"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} --only-validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on nonexisting clusters: PASS"
  else
    echo "Fails on nonexisting clusters: FAIL"
    ((++FAILURES))
  fi

  #################
  # Should fail on bad CA or MODE
  #################

  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m this_should_fail"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on bad mode: PASS"
  else
    echo "Fails on bad mode: FAIL"
    ((++FAILURES))
  fi


  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m migrate"
  CMD="${CMD} -c this_should_fail"
  CMD="${CMD} --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on bad CA: PASS"
  else
    echo "Fails on bad CA: FAIL"
    ((++FAILURES))
  fi

  #################
  # Should fail on with only one of key/service account
  #################

  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m install"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} -s service-account"
  CMD="${CMD} --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on only SA: PASS"
  else
    echo "Fails on only SA: FAIL"
    ((++FAILURES))
  fi


  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m install"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} -k keyfile"
  CMD="${CMD} --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on only key: PASS"
  else
    echo "Fails on only key: FAIL"
    ((++FAILURES))
  fi

  #################
  # Should fail to install if Istio installed
  #################

  CMD="-l this_should_pass_has_istio_right_namespace"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m install"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on installing with Istio: PASS"
  else
    echo "Fails on installing with Istio: FAIL"
    ((++FAILURES))
  fi

  #################
  # Should fail to do anything if it's in the wrong namespace
  #################

  CMD="-l this_should_pass_has_istio_wrong_namespace"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m migrate"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on migrating with Istio outside of istio-system: PASS"
  else
    echo "Fails on migrating with Istio outside of istio-system: FAIL"
    ((++FAILURES))
  fi

  #################
  # Should fail if enable* passed with only-validate
  #################

  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m migrate"
  CMD="${CMD} -c mesh_ca"
  CMD="${CMD} -e --only_validate"

  RETVAL=0
  clear_variables
  _="$(main ${CMD})" || RETVAL="${?}"

  if [[ "${RETVAL}" -ne 0 ]]; then
    echo "Fails on using enable* with --only-validate: PASS"
  else
    echo "Fails on using enable* with --only-validate: FAIL"
    ((++FAILURES))
  fi

  #################
  # Below we're testing that what permissions we use match the flags
  #################

  CMD="-l this_should_pass"
  CMD="${CMD} -n this_should_pass"
  CMD="${CMD} -p this_should_pass"
  CMD="${CMD} -m install"
  CMD="${CMD} -c mesh_ca"

  clear_variables
  parse_args ${CMD}

  if can_modify_cluster_roles \
    || can_modify_cluster_labels \
    || can_modify_gcp_apis \
    || can_modify_gcp_components \
    || can_modify_gcp_iam_roles; then
    echo "Permissions with no flags: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with no flags: PASS"
  fi

  clear_variables
  parse_args ${CMD} -e

  if ! can_modify_at_all \
    || ! can_modify_cluster_roles \
    || ! can_modify_cluster_labels \
    || ! can_modify_gcp_apis \
    || ! can_modify_gcp_components \
    || ! can_modify_gcp_iam_roles; then
    echo "Permissions with --enable-all flag: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with --enable-all flag: PASS"
  fi

  clear_variables
  parse_args ${CMD} --enable-cluster-labels

  if ! can_modify_at_all \
    || can_modify_cluster_roles \
    || ! can_modify_cluster_labels \
    || can_modify_gcp_apis \
    || can_modify_gcp_components \
    || can_modify_gcp_iam_roles; then
    echo "Permissions with --enable-cluster-labels flag: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with --enable-cluster-labels flag: PASS"
  fi

  clear_variables
  parse_args ${CMD} --enable-cluster-roles

  if ! can_modify_at_all \
    || ! can_modify_cluster_roles \
    || can_modify_cluster_labels \
    || can_modify_gcp_apis \
    || can_modify_gcp_components \
    || can_modify_gcp_iam_roles; then
    echo "Permissions with --enable-cluster-roles flag: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with --enable-cluster-roles flag: PASS"
  fi

  clear_variables
  parse_args ${CMD} --enable-gcp-apis

  if ! can_modify_at_all \
    || can_modify_cluster_roles \
    || can_modify_cluster_labels \
    || ! can_modify_gcp_apis \
    || can_modify_gcp_components \
    || can_modify_gcp_iam_roles; then
    echo "Permissions with --enable-gcp-apis flag: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with --enable-gcp-apis flag: PASS"
  fi

  clear_variables
  parse_args ${CMD} --enable-gcp-components

  if ! can_modify_at_all \
    || can_modify_cluster_roles \
    || can_modify_cluster_labels \
    || can_modify_gcp_apis \
    || ! can_modify_gcp_components \
    || can_modify_gcp_iam_roles; then
    echo "Permissions with --enable-gcp-components flag: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with --enable-gcp-components flag: PASS"
  fi

  clear_variables
  parse_args ${CMD} --enable-gcp-iam-roles

  if ! can_modify_at_all \
    || can_modify_cluster_roles \
    || can_modify_cluster_labels \
    || can_modify_gcp_apis \
    || can_modify_gcp_components \
    || ! can_modify_gcp_iam_roles; then
    echo "Permissions with --enable-gcp-iam-roles flag: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with --enable-gcp-iam-roles flag: PASS"
  fi

  clear_variables
  parse_args ${CMD} --managed

  if ! can_modify_at_all \
    || ! can_modify_cluster_roles \
    || can_modify_cluster_labels \
    || can_modify_gcp_apis \
    || ! can_modify_gcp_components \
    || ! can_modify_gcp_iam_roles; then
    echo "Permissions with --managed flag: FAIL"
    ((++FAILURES))
  else
    echo "Permissions with --managed flag: PASS"
  fi
  #################
  echo "There were ${FAILURES} failures."
  exit "${FAILURES}"
}

test_main "$@"
