#!/bin/bash

set -CeEu
set -o pipefail

SPATH="$(readlink -f "$0")"
SDIR="$(dirname "${SPATH}")"
# shellcheck source=common.sh
. "${SDIR}/common.sh"

LT_CLUSTER_NAME="long-term-test-cluster"
LT_CLUSTER_LOCATION="us-central1-c"
LT_PROJECT_ID="asm-scriptaro-oss"

RESULT="$(gcloud container clusters list \
  --project="${LT_PROJECT_ID}" \
  --filter="name = ${LT_CLUSTER_NAME} and location = ${LT_CLUSTER_LOCATION}" \
  --format="value(name)" || true)"

if [[ -n "${RESULT}" ]]; then
  echo "Long term test cluster exists already."
  configure_kubectl "${LT_CLUSTER_NAME}" "${LT_PROJECT_ID}" "${LT_CLUSTER_LOCATION}"
  remove_ns istio-system || true
  remove_ns asm-system || true
  exit
fi

echo "Creating long term test cluster"

gcloud beta container \
  --project "${LT_PROJECT_ID}" \
  clusters create "${LT_CLUSTER_NAME}" \
  \
  --zone "${LT_CLUSTER_LOCATION}" \
  --no-enable-basic-auth \
  --cluster-version "1.17.14-gke.400" \
  --release-channel "regular" \
  --machine-type "e2-standard-4" \
  --image-type "COS" \
  --disk-type "pd-standard" \
  --disk-size "100" \
  --metadata disable-legacy-endpoints=true \
  --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
  --num-nodes "4" \
  --enable-stackdriver-kubernetes \
  --enable-ip-alias \
  --network "projects/${LT_PROJECT_ID}/global/networks/default" \
  --subnetwork "projects/${LT_PROJECT_ID}/regions/us-central1/subnetworks/default" \
  --default-max-pods-per-node "110" \
  --enable-autoscaling \
  --min-nodes "4" \
  --max-nodes "100" \
  --no-enable-master-authorized-networks \
  --addons HorizontalPodAutoscaling,HttpLoadBalancing \
  --enable-autoupgrade \
  --enable-autorepair \
  --max-surge-upgrade 1 \
  --max-unavailable-upgrade 0 \
  --workload-pool "${LT_PROJECT_ID}.svc.id.goog" \
  --enable-shielded-nodes

echo "Performing necessary cluster setup"

../install_asm \
  -l ${LT_CLUSTER_LOCATION} \
  -n "${LT_CLUSTER_NAME}" \
  -p "${LT_PROJECT_ID}" \
  -m install \
  --only-enable -e
