# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stackdriver
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: stackdriver
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: stackdriver.googleapis.com
---
# GCE
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: compute
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: compute.googleapis.com
---
# GKE
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: gke
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: container.googleapis.com
---
# Short lived iam credentials for workload identity
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: iamcredentials
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: iamcredentials.googleapis.com
---
# Mesh Certificate Authority
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: meshca
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: meshca.googleapis.com
---
# Mesh Telemetry
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: meshtelemetry
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: meshtelemetry.googleapis.com
---
# Mesh Config
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: meshconfig
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: meshconfig.googleapis.com
---
# Anthos
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: anthos
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  service: anthos.googleapis.com
